### ISSUE TITLE
这个项目有相关的论文可以借鉴的吗？

### ISSUE THREAD

**Issue by icsaas** [willard-yuan/py-cbir-image-search-engine#1]

**Comment by icsaas** [comment]
Hi，
跟这篇blog http://blog.csdn.net/loadstar_kun/article/details/39450137 有什么不同吗？

**Comment by willard-yuan** [comment]
没有，是《Programming Computer Vision with Python》里的，用的是BOW模型+倒排索引，你可以看看图像检索那一章。

**Comment by icsaas** [comment]
ok！thanks

**Comment by willard-yuan** [comment]
方法就是那个，博客里用的是surf，这个用的是sift.

**Comment by willard-yuan** [comment]
我刚看了那篇博客，我觉得将BOF和哈希结合起来，可以做到实时。

**Comment by icsaas** [comment]
对了，有什么好的哈希资料介绍的没，那个ITQ能和BOF结合吗？

**Comment by willard-yuan** [comment]
那个cbir图像群里面我传了一些ppt，ppt前面有讲哈希是怎么回事的。ITQ和BOF结合起来完全是可以的，哈希过程相当于粗过滤（有的还有拉近相似图像的作用），可以一试，ITQ的代码用python写也很简单。
